[build]
  command = "npm run build"
  publish = ".next"
  functions = "netlify/functions"

[functions]
  directory = "netlify/functions"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[build.environment]
  NEXT_PUBLIC_HELIO_API_KEY = ""
  HELIO_API_SECRET = ""
  HELIO_SHARED_TOKEN = ""
  NEXT_PUBLIC_SITE_URL = ""
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "dummy"
  NEXT_PUBLIC_SUPABASE_DATABASE_URL = "dummy"
  NEXT_PUBLIC_SUPABASE_URL = "dummy"
  SUPABASE_ANON_KEY = "dummy"
  SUPABASE_DATABASE_URL = "dummy"
  SUPABASE_JWT_SECRET = "dummy"
  SUPABASE_SERVICE_ROLE_KEY = "dummy"
  VITE_ULTRAMSG_TOKEN = ""

# Configurações de cache
[[headers]]
  for = "/*"
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache do Next.js
[cache]
  directory = ".next/cache"
  paths = [
    ".next/cache",
    "node_modules/.cache"
  ] 